//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinesWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Id { get; set; }
        public string car_num { get; set; }
        public string region { get; set; }
        public string licence_num { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string photo { get; set; }
    }
}
